export const Icons = {
  search: require('../../../assets/search.png'),
  setting: require('../../../assets/setting.png'),
  cancel: require('../../../assets/cancel.png'),
  leftArrow: require('../../../assets/leftArrow.png'),
  calendar: require('../../../assets/calendar.png'),
  '01d': require('../../../assets/01d.png'),
  '01n': require('../../../assets/01d.png'),
  '02d': require('../../../assets/02d.png'),
  '02n': require('../../../assets/02d.png'),
  '03d': require('../../../assets/03d.png'),
  '03n': require('../../../assets/03d.png'),
  '04d': require('../../../assets/04d.png'),
  '04n': require('../../../assets/04d.png'),
  '09d': require('../../../assets/09d.png'),
  '10d': require('../../../assets/10d.png'),
  '10n': require('../../../assets/10d.png'),
  '11d': require('../../../assets/11d.png'),
  '11n': require('../../../assets/11d.png'),
  '13d': require('../../../assets/13d.png'),
  '13n': require('../../../assets/13d.png'),
  '50d': require('../../../assets/50d.png'),
  '50n': require('../../../assets/50d.png'),
};
